apiVersion: v1
kind: Pod
metadata:
  name: rsync-server
  namespace: hub
  labels:
    app: jupyterhub
    component: singleuser-server
    ssh-bastion-server/notebook: "true"
    role: rsync-server
    managed-by: TaoKan
    mountPvc: claim-kent # Fill correct data
spec:
  containers:
    - image: infuseai/rsync-server:latest
      imagePullPolicy: Always
      name: rsync-server
      volumeMounts:
        - mountPath: /data
          name: data-volume
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 512Mi
      env:
        - name: SSH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: rsync-ssh-key
              key: publickey
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: claim-kent # Fill correct data
