apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: primehub-group
    primehub-group: za
    role: nfs-server
  name: data-nfs-project-za-0
  namespace: hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
