#! /bin/bash
IFS=$'\n'

log_path=${1:-./backup_log}
data_path="${log_path}/.."

if [ ! -d $log_path ]; then
    echo "Usage: $(basename $0) [<rsync-log-path>]"
    exit 1
fi


update_counter=0
create_counter=0
missing_counter=0
RE=.+-[0-9]+-[0-9]+-[0-9]+-[0-9]+.log
for f in $(ls ${log_path})
do
    if [[ $f =~ $RE ]]; then
        for data in $(cat $log_path/$f)
        do
            itemize=$(echo "$data" | awk '{print $4}')
            if [ "${itemize:0:2}" == "<f" ]; then
                file=$(echo $data | awk '{print $5}' )
                if [ -f "$data_path/$file" ]; then
                    if [ "${itemize:2:3}" == "c" ]; then
                      echo "$file -> updated"
                      update_counter=(($update_counter+1))
                    else
                      echo "$file -> copied"
                      create_counter=(($create_counter+1))
                    fi
                else
                    echo "$file -> missing"
                    missing_counter=(($missing_counter+1))
                fi
            fi
        done
    fi
done

echo ""
echo "Number of created files: $create_counter"
echo "Number of updated files: $update_counter"
echo "Number of missing files: $missing_counter"
