apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "TaoKanOperator.fullname" . }}
  labels:
    {{- include "TaoKanOperator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "TaoKanOperator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "TaoKanOperator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "TaoKanOperator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - taokan
          args:
            {{- if .Values.taoKan.serverMode }}
            - "server"
            - "--port"
            - "22"
            - "--namespace"
            - "{{ .Release.Namespace }}"
            {{- else }}
            - "client"
            - "--remote"
            - "{{ required "A valid .Values.taoKan.remoteCluster entry required!" .Values.taoKan.remoteCluster }}"
            - "--port"
            - "{{ .Values.taoKan.remotePort }}"
            - "--namespace"
            - "{{ .Release.Namespace }}"
            {{- end }}
          {{- if .Values.taoKan.serverMode }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
