name: Build TaoKan Operator
on:
  release:
    types: created

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build & deploy images
        run: make deploy VERSION=${{ github.event.release.tag_name }} && make build-image-tarball VERSION=${{ github.event.release.tag_name }}
      - name: Build helm chart
        run: make package-helm-chart VERSION=${{ github.event.release.tag_name }}
      - name: Upload helm chart tarball
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: TaoKanOperator-${{ github.event.release.tag_name }}.tar.gz
          asset_name: TaoKanOperator-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload image tarball
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: taokan-${{ github.event.release.tag_name }}.tgz
          asset_name: taokan-${{ github.event.release.tag_name }}.tgz
          asset_content_type: application/tar+gzip
      - name: Upload image tarball list
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: taokan-${{ github.event.release.tag_name }}.txt
          asset_name: taokan-${{ github.event.release.tag_name }}.txt
          asset_content_type: application/text
